
app.use('/', (err,req, res, next) => {
  res.status(500).send('something went wrong')  
})

app.get('/userError', (req, res, next) => {
  try {

    throw new Error
  }
  catch (err) {
    res.send('error occured')
  }
});
